### ISSUE TITLE
Translate string missing

### ISSUE THREAD

**Issue by EKE00372** [brittyazel/EnhancedRaidFrames#104]
## Is your feature request related to a problem? Please describe:
I'm doing translate and seems some strings are missing.
such like middle/top left/offset/curse....etc.

## Describe the solution you'd like to see implemented:
just add them !_!

**Comment by brittyazel** [comment]
I have updated the strings, but Curseforge crashed during the import and it seems like many of the translations got corrupted. I manually restored the translations that existed in the prior release for the time being, and I have opened a ticket with Curseforge support to see if they can help us out. Apologies if you lost any work.
