### ISSUE TITLE
Cannot show full option

### ISSUE THREAD

**Issue by EKE00372** [brittyazel/EnhancedRaidFrames#106]
## Issue description:
It's an ZH only issue I think.

![image](https://github.com/brittyazel/EnhancedRaidFrames/assets/1412472/86207d81-5b27-4c2b-afbb-d13c7afce542)

It should be
`只顯示我獲得`
`的光環`
but it didn't because no enough space......?

**Comment by brittyazel** [comment]
Hrm. I can maybe widen the column a bit, but it's Ace3 that is dictating the text formatting and there's not a lot I can do about it

**Comment by EKE00372** [comment]
can we get options one by one line, or show describe as tooltip instead a text block?

**Comment by brittyazel** [comment]
We can, but I like the way the text in English looked written into the column itself.  Having it just be a mouseover tooltip makes the window look too empty. We can try it though. We just need to remove the "descStyle = "inline" lines

**Comment by brittyazel** [comment]
I have slightly widened the column widths. Please let me know if that makes any difference

**Comment by brittyazel** [comment]
The only only thing we could do (besides converting to a mouseover tooltip) would be to adjust the string to be shorter

**Comment by EKE00372** [comment]
1.25 will make options warp.
![image](https://github.com/brittyazel/EnhancedRaidFrames/assets/1412472/42695ad4-f8ff-45a4-a04c-6b99fa8d35d0)

1.14 will make another options missing.
![image](https://github.com/brittyazel/EnhancedRaidFrames/assets/1412472/3185a8ee-48f3-4c20-9a21-aa8f83dbede6)

**Comment by brittyazel** [comment]
Alright, we can go with a mouseover tooltip. I'll delete those lines tomorrow.

**Comment by EKE00372** [comment]
Btw zhTW locale Initially completed. will do zhCN later.

**Comment by EKE00372** [comment]
zhCN done.
