### ISSUE TITLE
ACE3 Libs error on PTR

### ISSUE THREAD

**Issue by EKE00372** [brittyazel/EnhancedRaidFrames#107]
`Interface/AddOns/Ace3/AceDB-3.0/AceDB-3.0.lua:264: attempt to concatenate local 'regionKey' (a nil value)`

Probably a lib issue happened because PTR region changed since 10.1.5, should update libs.

ps. do a wrong spell on zhcn `Horizontal Offset` before, already correct it in curse, need sync.

**Comment by brittyazel** [comment]
Hrm is this actually to do with Enhanced Raid Frames? Do you have the full lua error so I can see which line triggers it?

If it's an issue with upstream Ace3, then I'll definitely get a newer stable version included asap.

**Comment by brittyazel** [comment]
New version released
