### ISSUE TITLE
Interested in contributing a feature...

### ISSUE THREAD

**Issue by opensrcery** [brittyazel/EnhancedRaidFrames#11]
Veteran programmer interested in contributing the ability to set multiple icons per indicator. Currently have a very hacky implementation of this in my addon.

Not experienced with lua although it looks very simple.

Not experienced w/ the WoW or Ace API's.

If you are interested in this feature as well, but don't want to implement it yourself, throw me some pointers and I'll try to put something together in my free time.

**Comment by brittyazel** [comment]
Absolutely I'd love for assistance on enhancing this add-on! I've had lots of ideas on things I've wanted to add, but not enough time to actually see many of them through.

To get started, I suggest following my instructions in the README of my other add-on, Neuron, in getting your Dev environment set up. I suggest Intellij as the best LUA IDE that I've tried. After following that setup you will have full code completion and real time syntax checking, which is super great for getting your feet wet. And yes, LUA is SUPER easy, it just takes a min to get used to the whole "everything is a table" concept.

**Comment by brittyazel** [comment]
https://github.com/Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API/wiki

This is the guide I used to get myself set up.

**Comment by brittyazel** [comment]
I'm closing this as it never seemed to materialize. Thanks for the thought though
