### ISSUE TITLE
[BUG] LUA errors: calling 'IsShown' on bad self

### ISSUE THREAD

**Issue by Fels-wow** [brittyazel/EnhancedRaidFrames#112]
Hi Brittyazel,

I'm getting the following 2 LUA errors in 3.7.2 and 3.7.1. But not in 3.7.0.

This is the result of 1 timewalking dungeon (to test). I 'wiped saved bugs' in BugSack just before the dungen started.

Thx for your work on this great addon, Fels

--------------------------------------------

154x EnhancedRaidFrames/UtilitiesAndOverrides.lua:75: calling 'IsShown' on bad self (Usage: local isShown = self:IsShown())
[string "=[C]"]: in function `IsShown'
[string "@EnhancedRaidFrames/UtilitiesAndOverrides.lua"]:75: in function `UpdateInRange'
[string "@EnhancedRaidFrames/EnhancedRaidFrames.lua"]:89: in function <...aceEnhancedRaidFrames/EnhancedRaidFrames.lua:89>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `CompactUnitFrame_UpdateInRange'
[string "@FrameXML/CompactUnitFrame.lua"]:413: in function <FrameXML/CompactUnitFrame.lua:395>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAll'
[string "@FrameXML/CompactUnitFrame.lua"]:242: in function `CompactUnitFrame_SetUnit'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:546: in function `OnAdded'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:142: in function `OnNamePlateAdded'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:78: in function <...eBlizzard_NamePlates/Blizzard_NamePlates.lua:69>

Locals:
(*temporary) = Button {
 0 = <userdata>
 WidgetContainer = Frame {
 }
 classificationIndicator = Texture {
 }
 RaidTargetFrame = Frame {
 }
 maxDispelDebuffs = 0
 inVehicle = false
 optionTable = <table> {
 }
 overAbsorbGlow = Texture {
 }
 SoftTargetFrame = Frame {
 }
 totalAbsorb = Texture {
 }
 name = FontString {
 }
 aggroHighlight = Texture {
 }
 needsUpdate = true
 myHealAbsorbRightShadow = Texture {
 }
 overHealAbsorbGlow = Texture {
 }
 newUnit = true
 ignoreCUFNameRequirement = true
 selectionHighlight = Texture {
 }
 myHealAbsorbLeftShadow = Texture {
 }
 maxDebuffs = 0
 unit = "nameplate1"
 unitExists = true
 disableMouse = true
 healPredictionDirty = true
 hideCastbar = false
 castBar = StatusBar {
 }
 hideHealthBarMask = 0
 BuffFrame = Frame {
 }
 ClassificationFrame = Frame {
 }
 LoseAggroAnim = AnimationGroup {
 }
 myHealAbsorb = Texture {
 }
 maxBuffs = 0
 totalAbsorbOverlay = Texture {
 }
 otherHealPrediction = Texture {
 }
 myHealPrediction = Texture {
 }
 displayedUnit = "nameplate1"
 healthBar = StatusBar {
 }
}

-------------------------------------------------------------------

1758x EnhancedRaidFrames/UtilitiesAndOverrides.lua:49: calling 'IsShown' on bad self (Usage: local isShown = self:IsShown())
[string "=[C]"]: in function `IsShown'
[string "@EnhancedRaidFrames/UtilitiesAndOverrides.lua"]:49: in function `SetStockIndicatorVisibility'
[string "@EnhancedRaidFrames/EnhancedRaidFrames.lua"]:86: in function <...aceEnhancedRaidFrames/EnhancedRaidFrames.lua:86>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML/CompactUnitFrame.lua"]:419: in function <FrameXML/CompactUnitFrame.lua:395>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAll'
[string "@FrameXML/CompactUnitFrame.lua"]:242: in function `CompactUnitFrame_SetUnit'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:546: in function `OnAdded'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:142: in function `OnNamePlateAdded'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:78: in function <...eBlizzard_NamePlates/Blizzard_NamePlates.lua:69>

Locals:
(*temporary) = Button {
 0 = <userdata>
 debuffs = <table> {
 }
 WidgetContainer = Frame {
 }
 classificationIndicator = Texture {
 }
 RaidTargetFrame = Frame {
 }
 maxDispelDebuffs = 0
 inVehicle = false
 optionTable = <table> {
 }
 overAbsorbGlow = Texture {
 }
 SoftTargetFrame = Frame {
 }
 totalAbsorb = Texture {
 }
 name = FontString {
 }
 aggroHighlight = Texture {
 }
 needsUpdate = true
 myHealAbsorbRightShadow = Texture {
 }
 overHealAbsorbGlow = Texture {
 }
 newUnit = true
 ignoreCUFNameRequirement = true
 selectionHighlight = Texture {
 }
 myHealAbsorbLeftShadow = Texture {
 }
 maxDebuffs = 0
 unit = "nameplate1"
 unitExists = true
 disableMouse = true
 buffs = <table> {
 }
 healPredictionDirty = true
 hideCastbar = false
 castBar = StatusBar {
 }
 dispels = <table> {
 }
 hideHealthBarMask = 0
 BuffFrame = Frame {
 }
 ClassificationFrame = Frame {
 }
 LoseAggroAnim = AnimationGroup {
 }
 myHealAbsorb = Texture {
 }
 maxBuffs = 0
 totalAbsorbOverlay = Texture {
 }
 otherHealPrediction = Texture {
 }
 myHealPrediction = Texture {
 }
 displayedUnit = "nameplate1"
 healthBar = StatusBar {
 }
}

**Comment by brittyazel** [comment]
Thanks for the report! I added some protections in to keep this from happening again. New build coming out asap.

**Comment by Fels-wow** [comment]
Thx for your quick action! Much appreciated! Unfortunately the bug still persist in 3.7.3

-----------------------------------------------


13x EnhancedRaidFrames/UtilitiesAndOverrides.lua:83: calling 'IsShown' on bad self (Usage: local isShown = self:IsShown())
[string "=[C]"]: in function `IsShown'
[string "@EnhancedRaidFrames/UtilitiesAndOverrides.lua"]:83: in function `UpdateInRange'
[string "@EnhancedRaidFrames/EnhancedRaidFrames.lua"]:89: in function <...aceEnhancedRaidFrames/EnhancedRaidFrames.lua:89>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `CompactUnitFrame_UpdateInRange'
[string "@FrameXML/CompactUnitFrame.lua"]:413: in function <FrameXML/CompactUnitFrame.lua:395>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAll'
[string "@FrameXML/CompactUnitFrame.lua"]:242: in function `CompactUnitFrame_SetUnit'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:546: in function `OnAdded'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:142: in function `OnNamePlateAdded'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:78: in function <...eBlizzard_NamePlates/Blizzard_NamePlates.lua:69>

Locals:
(*temporary) = Button {
 0 = <userdata>
 WidgetContainer = Frame {
 }
 classificationIndicator = Texture {
 }
 RaidTargetFrame = Frame {
 }
 maxDispelDebuffs = 0
 inVehicle = false
 optionTable = <table> {
 }
 overAbsorbGlow = Texture {
 }
 SoftTargetFrame = Frame {
 }
 totalAbsorb = Texture {
 }
 name = FontString {
 }
 aggroHighlight = Texture {
 }
 needsUpdate = true
 myHealAbsorbRightShadow = Texture {
 }
 overHealAbsorbGlow = Texture {
 }
 newUnit = true
 ignoreCUFNameRequirement = true
 selectionHighlight = Texture {
 }
 myHealAbsorbLeftShadow = Texture {
 }
 maxDebuffs = 0
 unit = "nameplate1"
 unitExists = true
 disableMouse = true
 healPredictionDirty = true
 hideCastbar = false
 castBar = StatusBar {
 }
 hideHealthBarMask = 0
 BuffFrame = Frame {
 }
 ClassificationFrame = Frame {
 }
 LoseAggroAnim = AnimationGroup {
 }
 myHealAbsorb = Texture {
 }
 maxBuffs = 0
 totalAbsorbOverlay = Texture {
 }
 otherHealPrediction = Texture {
 }
 myHealPrediction = Texture {
 }
 displayedUnit = "nameplate1"
 healthBar = StatusBar {
 }
}




-----------------------------------------------

337x EnhancedRaidFrames/UtilitiesAndOverrides.lua:53: calling 'IsShown' on bad self (Usage: local isShown = self:IsShown())
[string "=[C]"]: in function `IsShown'
[string "@EnhancedRaidFrames/UtilitiesAndOverrides.lua"]:53: in function `SetStockIndicatorVisibility'
[string "@EnhancedRaidFrames/EnhancedRaidFrames.lua"]:86: in function <...aceEnhancedRaidFrames/EnhancedRaidFrames.lua:86>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML/CompactUnitFrame.lua"]:419: in function <FrameXML/CompactUnitFrame.lua:395>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAll'
[string "@FrameXML/CompactUnitFrame.lua"]:242: in function `CompactUnitFrame_SetUnit'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:546: in function `OnAdded'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:142: in function `OnNamePlateAdded'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:78: in function <...eBlizzard_NamePlates/Blizzard_NamePlates.lua:69>

Locals:
(*temporary) = Button {
 0 = <userdata>
 debuffs = <table> {
 }
 WidgetContainer = Frame {
 }
 classificationIndicator = Texture {
 }
 RaidTargetFrame = Frame {
 }
 maxDispelDebuffs = 0
 inVehicle = false
 optionTable = <table> {
 }
 overAbsorbGlow = Texture {
 }
 SoftTargetFrame = Frame {
 }
 totalAbsorb = Texture {
 }
 name = FontString {
 }
 aggroHighlight = Texture {
 }
 needsUpdate = true
 myHealAbsorbRightShadow = Texture {
 }
 overHealAbsorbGlow = Texture {
 }
 newUnit = true
 ignoreCUFNameRequirement = true
 selectionHighlight = Texture {
 }
 myHealAbsorbLeftShadow = Texture {
 }
 maxDebuffs = 0
 unit = "nameplate1"
 unitExists = true
 disableMouse = true
 buffs = <table> {
 }
 healPredictionDirty = true
 hideCastbar = false
 castBar = StatusBar {
 }
 dispels = <table> {
 }
 hideHealthBarMask = 0
 BuffFrame = Frame {
 }
 ClassificationFrame = Frame {
 }
 LoseAggroAnim = AnimationGroup {
 }
 myHealAbsorb = Texture {
 }
 maxBuffs = 0
 totalAbsorbOverlay = Texture {
 }
 otherHealPrediction = Texture {
 }
 myHealPrediction = Texture {
 }
 displayedUnit = "nameplate1"
 healthBar = StatusBar {
 }
}

**Comment by brittyazel** [comment]
Alright, attempt #2. This one should stick I hope. Honestly, I'm dumbfounded why this is happening in the first place, there's really no logical explanation for it that I can think of lol. Nevertheless, I removed the condition that was triggering the bug.

**Comment by Fels-wow** [comment]
Thx alot Brittyazel! Tested a couple of dungeon. Conclusion: completely solved
