### ISSUE TITLE
[BUG] Regression: Icon for indicator doesn't show

### ISSUE THREAD

**Issue by the-isz** [brittyazel/EnhancedRaidFrames#114]
## Issue description:
- The icon for debuffs doesn't show

## How to reproduce:
1. Enable "Use Raid-Style Party Frames" (Edit Mode)
1. In ERF options, set Top-Right indicator to

        Poison
        Disease
        Magic

1. Check "Show Icon"
1. Join party, wait for team member to gain debuff
1. Observe that the default, generic debuff icon still shows instead of the particular debuff (e.g. the generic blue icon for magic debuffs instead of the icon for Chronoburst).

## Technical info:
 - Addon Version: 10.2.0
 - Client: Retail
 - Client Patch Version: 10.2.0 (52148)
 
## Additional context:
- This used to work prior to 10.2.0
- Thanks for this great addon!

**Comment by brittyazel** [comment]
Yeah I too was having issue with this. I may have resolved this in the Main branch already, I just haven't pushed the new update until I finished my raid testing with my raid group this week. Almost all the post-10.2 testing was done piecemeal and not holistically in an actual raid environment.

**Comment by brittyazel** [comment]
@the-isz can you confirm if this is fixed or not?

**Comment by the-isz** [comment]
@brittyazel: I need to check again later, but I think I saw it working after yesterday's update.

Thank you!
