### ISSUE TITLE
Distinction between buffs and debuffs when tracking 

### ISSUE THREAD

**Issue by tw1ZTER** [brittyazel/EnhancedRaidFrames#116]
Implement an option that tracks either buffs or debuffs.
This issue comes from the trinket Blossom of Amirdrassil, the buff effect and the debuff cooldown aura shares the same name, so both show on frames when either it activates or its on cd.
![Screenshot_26](https://github.com/brittyazel/EnhancedRaidFrames/assets/81321054/2a57336d-7843-4b8c-92dd-2260682047fc)
![Screenshot_27](https://github.com/brittyazel/EnhancedRaidFrames/assets/81321054/0490004d-2aad-4009-98ac-08ff5831bd50)
Thank you very much :^)

**Comment by tw1ZTER** [comment]
![image](https://github.com/brittyazel/EnhancedRaidFrames/assets/81321054/b077f69d-be3f-400a-8727-d25c40c72647)
another image of the debuff aura

**Comment by brittyazel** [comment]
For the time being can you use the spell ID to track this instead? Each type should have a different spell ID

**Comment by tw1ZTER** [comment]
Doesnt seems to be working with either the spell ID or the item ID.
![image](https://github.com/brittyazel/EnhancedRaidFrames/assets/81321054/0dc7d948-d66d-44b2-a241-3c471331acdf)
![image](https://github.com/brittyazel/EnhancedRaidFrames/assets/81321054/028d24fc-3d53-439e-ac43-a88e7848c964)
![image](https://github.com/brittyazel/EnhancedRaidFrames/assets/81321054/29a669c5-d639-46df-9521-88897417f643)

**Comment by tw1ZTER** [comment]
Nevermind, the ID listed in wowhead is incorrect, it does work with a correct id fetch by an addon. Ty!
