### ISSUE TITLE
[BUG]Icons not disappearing after buffs/debuffs expires

### ISSUE THREAD

**Issue by Pappajente** [brittyazel/EnhancedRaidFrames#118]
*When reporting, please verify the issue with only **this** addon enabled and no others unless explicitly reporting an
incompatibility between this addon. Likewise, please fill in the below information to the best of your ability — this
information helps us a great deal.*

## Issue description:

Icons are not disappearing after buff expires on the raid frame. I.e. PW:S icon does not disappear after the actual buff has expired.

## How to reproduce:

Cast any spell that produces a buff or debuff.

1. *Go to '....'*
2. *Click on '....'*
3. *Scroll down to '....'*
4. *See error*

## Technical info:

- **Addon Version:** *3.10.2*
- **Client:** *Classic wotlk]*
- **Client Patch Version: 3.4.3.52237*

## Additional context:

*Add any other context about the problem here.*

## Screenshots:

*If applicable, add screenshots to help explain your problem.*

## Lua error log:

*Attach the Lua error log here (please use code tags)*

**Comment by brittyazel** [comment]
Thanks for the report. I think I know what is causing this and can have a fix out asap.
