### ISSUE TITLE
Making icons click through

### ISSUE THREAD

**Issue by badeanda** [brittyazel/EnhancedRaidFrames#120]
Hi there,

Is it possible to get this feature for enhanced raid frames? Even if i toggle the tooltip off, mouseover addons like Clique or mouseover macros doesn't work if the mouse is hovering over the icon.

Thanks in advance for your time.

**Comment by brittyazel** [comment]
Hrm, the icons are click through, as you can see [here](https://github.com/brittyazel/EnhancedRaidFrames/blob/82cd7f3550a5025faccc400a7ee9789d3ae536cb/Modules/AuraIndicators.lua#L48).

I wonder if there is another setting I should set for the case of mouseover macros. It depends on the logic for how those features work tbh. Right now the indicator icons are already children of the raid frame, and they're set to ignore mouse clicks. Unfortunately, I'm not sure of what more I can do TBH.

**Comment by badeanda** [comment]
> Hrm, the icons are click through, as you can see [here](https://github.com/brittyazel/EnhancedRaidFrames/blob/82cd7f3550a5025faccc400a7ee9789d3ae536cb/Modules/AuraIndicators.lua#L48).
> 
> I wonder if there is another setting I should set for the case of mouseover macros. It depends on the logic for how those features work tbh. Right now the indicator icons are already children of the raid frame, and they're set to ignore mouse clicks. Unfortunately, I'm not sure of what more I can do TBH.

Yeah, i noticed that their possible to click through, it just isn't possible to mouseover heal when hovering over them. It creates a lot of "dead spots" for mouseover healing. KHM Raid Frames has the option to make them "click through", which also enables mouseover. This is all done on the default raid frames. I would much rather use your enhanced raid frames, as you can move the icon around.

**Comment by badeanda** [comment]
I would also like to add that i'm not at all the first one asking for this, there are plenty of questions out there regarding the same "issue".

**Comment by brittyazel** [comment]
The only thing I could think that could resolve this was if I I set :MouseEnable(false) on them, but that would break mouseover tooltips. I also have no idea if that would actually resolve this issue either. I can't find any source code where I can understand how the mouseover functionality works in-game.

**Comment by brittyazel** [comment]
@badeanda I just implemented a mouseover casting compatibility option in the main branch. Can you please test it and see if it works? If so, I'll push out a new version.
