### ISSUE TITLE
[BUG][Retail] Target marker icon on wrong unit

### ISSUE THREAD

**Issue by mbattersby** [brittyazel/EnhancedRaidFrames#125]
## Issue description:

At one point raiding today the target marker icon appeared on the wrong unit. Another time it persisted on a unit despite having been cleared.

Screenshot shows the second one (icon on target unit frame, definitely no icon on them)

I don't know if this is an ERF issue or a Blizzard issue but I thought I'd mention it. It's never happened before that I know of and I've been using this addon for at least 2 years.

## How to reproduce:

I have no idea.

## Technical info:

- **Addon Version:** 3.13.7
- **Client:** Retail
- **Client Patch Version:**  11.0.0.55824

## Additional context:

I have no other theories at this point,

## Screenshots:

![image](https://github.com/user-attachments/assets/46e8e227-3b67-4ec0-b462-427ecf35b5d7)

## Lua error log:

No errors displayed.

**Comment by mbattersby** [comment]
Here is another screenshot where you can see it on my raid unit frame but not on my player frame or on my model.

![image](https://github.com/user-attachments/assets/d4a24ae0-16b6-4390-a338-42d1f503a58e)

**Comment by brittyazel** [comment]
It's quite possible it's a combination of an ERF issue and an 11.0 issue. Blizzard broke A LOT of stuff in this latest patch, and us addon authors are still sifting through the wreckage lol. Though this one is odd, and I don't see where on ERF's end the issue would be, but I'll take a look.

My guild isn't raiding at the moment until the expansion launches, so finding raid groups to test this stuff on is hard to come by lol.

**Comment by brittyazel** [comment]
Do you know if there was an Lua error that accompanied this issue? Would you mind turning on Lua errors in case one pops up the next time this issue happens?

**Comment by mbattersby** [comment]
Definitely no lua error, I always have them enabled.

**Comment by mbattersby** [comment]
If I had to guess, I would suspect its happening when the raid group
membership is changing. Perhaps there's some event it's not catching to
rescan and it's stuck in the wrong place.

**Comment by brittyazel** [comment]
Yeah that was my thought as well. I added a full re-scan of the target markers upon a change to the group roster, so if the theory holds, this issue shouldn't happen any longer. Let's reopen if it does.
