### ISSUE TITLE
Pandemic glow

### ISSUE THREAD

**Issue by jacobrreed** [brittyazel/EnhancedRaidFrames#127]
## Is your feature request related to a problem? Please describe:
Not a problem, but I'd only like my watchlist buffs to glow in pandemic window, i.e less than 3 seconds

## Describe the solution you'd like to see implemented:
Number input next to Glow checkbox if checked, where i can enter pandemic window number i.e 3 seconds. Icon would only glow if that condition is meant

## Describe alternatives you've considered:
different addon maybe?

**Comment by brittyazel** [comment]
Correct me if I'm wrong, but doesn't that option already exist? I'm pretty sure I added that feature. Or am I misunderstanding?

Look for "Glow at Countdown Time" which has the description:
"The amount of time (in seconds) remaining on the buff or debuff countdown before the glowing starts"

**Comment by jacobrreed** [comment]
Oops ya you're right my bad
