### ISSUE TITLE
[BUG] Translation content is missing.

### ISSUE THREAD

**Issue by EKE00372** [brittyazel/EnhancedRaidFrames#128]
*When reporting, please verify the issue with only **this** addon enabled and no others unless explicitly reporting an
incompatibility between this addon. Likewise, please fill in the below information to the best of your ability — this
information helps us a great deal.*

## Issue description:

I just noticed that the translation progress is less than 50%. As I remember I submitted last June, then checking version 3.5.9 from last July, confirmed translations were accepted and included in the release at that time. Could you please restore them?

**Comment by brittyazel** [comment]
Hrm, translations are handled over on the Curseforge side. I'm not sure why they would have been removed....

Which locale is missing the translations?

**Comment by brittyazel** [comment]
Are you certain the translations were actually erroneously deleted? The strings have changed over time, and when a string changes the translation no longer aligns and Curseforge prunes them.
