### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Tasten4** [brittyazel/EnhancedRaidFrames#131]
Hello, getting this error in Phase 5 of SOD:

Message: .../AddOns/EnhancedRaidFrames/Modules/TargetMarkers.lua:112: attempt to index local 'coords' (a number value)
Time: Thu Sep 26 15:22:03 2024
Count: 16
Stack: .../AddOns/EnhancedRaidFrames/Modules/TargetMarkers.lua:112: attempt to index local 'coords' (a number value)
[string "@Interface/AddOns/EnhancedRaidFrames/Libs/AceBucket-3.0/AceBucket-3.0.lua"]:85: in function `func'
[string "@Interface/AddOns/Details/Libs/AceTimer-3.0/AceTimer-3.0.lua"]:57: in function <...ce/AddOns/Details/Libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals: bucket = <table> {
 received = <table> {
 }
 timer = <table> {
 }
 object = <table> {
 }
 interval = 0.250000
}
received = <table> {
 nil = 1
}
AceTimer = <table> {
 embeds = <table> {
 }
 activeTimers = <table> {
 }
}

**Comment by brittyazel** [comment]
Thanks for the report. I guess Blizzard finally caught WoW Classic up to retail for a number of these items. I can get a fix out in an hour or two.
