### ISSUE TITLE
Duration of group member buffs not visible

### ISSUE THREAD

**Issue by Dreadone** [brittyazel/EnhancedRaidFrames#22]
i can see the timer/clock of my own buffs but i cant see that info of other players in the group.
Their bufficons are visible fine. i dont have "mine only" enabled. I mean i can see them :) but not the remaining time. The clock thingy would be totaly enough.

**Comment by Dreadone** [comment]
<a href="https://ibb.co/YLh41NF"><img src="https://i.ibb.co/G5Rf8d4/frames.jpg" alt="frames" border="0"></a>

**Comment by brittyazel** [comment]
Your screenshot is of an outdated version of the addon. Can you please update to the latest and report back if you are still having the issue?

**Comment by Dreadone** [comment]
Latest build doesnt show addon options anymore. The addon works in the background becuase i can see the player buffs. But the options disappeared

**Comment by brittyazel** [comment]
Did you restart the game after updating? I can assure you the addon options exist and work

**Comment by Dreadone** [comment]
Deleted...reinstalled...reinstalled with the twitchap..deaktivated everything...nothing works.
Options are gone

<a href="https://ibb.co/cDYqxm0"><img src="https://i.ibb.co/yW42V3t/1.jpg" alt="1" border="0"></a>

<a href="https://imgbb.com/"><img src="https://i.ibb.co/3vv9CWL/2.jpg" alt="2" border="0"></a><br /><a target='_blank' href='https://de.imgbb.com/'>photo sharing</a><br />

**Comment by brittyazel** [comment]
Are you installing from Curseforge? The only thing I can think is that you are using the German client. Is it possible for you to test with the English client? Though I have no idea why it would have worked before but not now.... Are there any LUA errors? Is this on Classic or Retail?

**Comment by Dreadone** [comment]
Im installing via the twitch client. You see that on the third screenshot. Still using the german client. It worked fine before the last 1-2 Updates 😮

**Comment by brittyazel** [comment]
I figured it out. I added a new feature to retail to support per-spec profiles, and classic doesn't support profiles, and was resulting in an error. I added a conditional to check which version of the game is loaded so this won't happen.

**Comment by brittyazel** [comment]
New version 2.1.3 will work on Classic. Sorry I forgot that this bug wasn't the game not working, it was the buffs not being visible. Your original issue is only for Classic correct? I haven't played classic enough to be in any groups yet

**Comment by Dreadone** [comment]
i updated to the newest version..manualy copied from retail folder to classic folder and the options are back again! nice work :)

...but the duration of the other groupmembers still not showing :)

<a href="https://ibb.co/H7PHcTN"><img src="https://i.ibb.co/LSgZTdQ/new.jpg" alt="new" border="0"></a>

**Comment by brittyazel** [comment]
I wonder if this is a WoW Classic design limitation. On retail its working for me. Do you play retail? Can you verify it as well.

Unfortunately we use a function called UnitAura() for our checks, and if that function returns an icon (which we know it does) but not a duration then we're kinda stuck 😕 We're basically at the mercy of the information that this particular function hands back to us. Blizzard might have disabled duration reporting for out of range players perhaps because that's how it was in Vanilla

**Comment by stefan0uh** [comment]
I mean it can be wrapped with [LibClassicDurations](https://github.com/rgd87/LibClassicDurations)

**Comment by brittyazel** [comment]
This should be fixed by now. We've had LibClassicDurations for a while now
