### ISSUE TITLE
Glow on Icons

### ISSUE THREAD

**Issue by ChrisKayn** [brittyazel/EnhancedRaidFrames#34]
Last request. Theres a weakaura we healers use to track some debuffs that glows when a player has an specific debuff and this help us track dispels, hard heals, etc. It will be amazing if you can add Some type of GLOW to the icons as an option, and the option to add the glow when certain seconds are left on the aura, or just glow for the entire duration on an anchor. I think the glow code is on weakauras, im not good with programming with blizzards api, but this is another thing I just thought and I think it would help a LOT. Imagine be able to put glow on a CENTER ANCHOR, and be able to track whenever someone has an specific debuff that u need to dispel asap or something like that

**Comment by brittyazel** [comment]
I can try to add this. Hang tight

**Comment by brittyazel** [comment]
Done. I think you'll like it
