### ISSUE TITLE
Blacklisting spells and debuffs

### ISSUE THREAD

**Issue by Nimeva** [brittyazel/EnhancedRaidFrames#36]
A feature that lets users type in spell id's or names of whatever they want to blacklist, so that it never shows up in the raid frames and the ability to revert it again.
With that a list of all blacklisted spells and debuffs to see what is and what is not yet blacklisted.
The ability to show every debuff, edit these (make them bigger, smaller, and switch where they appear (just as it does with buffs now).

**Comment by brittyazel** [comment]
This is a copy of #5, please continue any relevant discussion there
