### ISSUE TITLE
Raid Issue Spam

### ISSUE THREAD

**Issue by ChrisKayn** [brittyazel/EnhancedRaidFrames#37]
I have been getting this error in raid just now, I had to desactivate the addon:

757x RaidFrameIndicators\AuraIndicators.lua:166: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: in function GetName' [string "@RaidFrameIndicators\AuraIndicators.lua"]:166: in function UpdateIndicators'
[string "@RaidFrameIndicators\EnhancedRaidFrames.lua"]:58: in function <...ceRaidFrameIndicators\EnhancedRaidFrames.lua:58>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML\CompactUnitFrame.lua"]:101: in function <FrameXML\CompactUnitFrame.lua:54>

Locals:
(*temporary) = ForbiddenNamePlate17UnitFrame {
0 =
WidgetContainer = {
}
classificationIndicator = {
}
castBar = {
}
maxDispelDebuffs = 0
inVehicle = false
optionTable =
{
}
overAbsorbGlow = {
}
totalAbsorb = {
}
myHealPrediction = {
}
aggroHighlight = {
}
hideCastbar = true
myHealAbsorbRightShadow = {
}
overHealAbsorbGlow = {
}
newUnit = true
selectionHighlight = {
}
myHealAbsorbLeftShadow = {
}
ClassificationFrame = {
}
unit = "nameplate17"
unitExists = true
disableMouse = true
otherHealPrediction = {
}
BuffFrame = {
}
name = {
}
totalAbsorbOverlay = {
}
myHealAbsorb = {
}
maxBuffs = 0
maxDebuffs = 0
RaidTargetFrame = {
}
healthBar = {
}
displayedUnit = "nameplate17"
LoseAggroAnim = {

**Comment by brittyazel** [comment]
What version of the add-on are you on? In the latest release (2.8.0) line 166 is a comment, so this error doesn't make much sense

**Comment by ChrisKayn** [comment]
yeah i just updated and its good now, before it wont stop spamming, thanks!
