### ISSUE TITLE
Issue with "Mine Only Tracking"

### ISSUE THREAD

**Issue by Amissia** [brittyazel/EnhancedRaidFrames#38]
The last two updates that were pushed 2.7.0 and 2.8.1 both have issues with Mine Only Tracking, but I haven't figured out exactly with how many spells. As an example, I play Holy Paladin and I was able to see not just my own, but other Paladin's glimmers despite having the "Mine Only" box ticked. I'm not sure how to provide anymore context on this because I'm not getting an error or anything. It just seems like the tracking isn't working properly.

**Comment by brittyazel** [comment]
Thanks for the report! I figured I missed something. I completely rewrote from the ground up the processing loop, and it appears I brain-farted on this one.

**Comment by brittyazel** [comment]
New version, 2.8.2, just published. It should be available on Curse/Twitch shortly

**Comment by Amissia** [comment]
Thank you!

**Comment by brittyazel** [comment]
Please report back and let me know if it fixes it! I'm cold testing these in a solo group so sometimes I don't spot issues that only manifest in real parties and raids

**Comment by Amissia** [comment]
I just did a test in a group and it worked wonderfully. If anything else
comes up I'll let you know!

**Comment by brittyazel** [comment]
appreciate it!
