### ISSUE TITLE
When raid member is dead, no indicators are displayed.

### ISSUE THREAD

**Issue by Oreo-hhh** [brittyazel/EnhancedRaidFrames#39]
Can you make so that I can see indicators when a dead raid frame is displayed? I want to be able to tell when a hunter is really dead or just showing dead due to Feign Death. What I am seeing when I add Feign Death as a buff to watch, the Feign Death icon is displayed very briefly right before the dead raid frame is shown. 

I am seeing this in World of Warcraft classic. I am not sure if it occurs or not in retail.

Thank you for your time. Big fan of the add on :)

**Comment by brittyazel** [comment]
Hrm I'm not sure I can to be honest. I'll play around with it. In general, dead players don't have indicators. I also didn't know that feign death would trick the games UnitIsDeadOrGhost() function into reporting "true". 

I'll play with it on Retail and see what I can do. I don't play classic nor do I have any toons there, so I'll do what I can but I'm flying blind

**Comment by Oreo-hhh** [comment]
If you need me test any changes, feel free to let me know. Its just a minor thing to me, if it can't be done, no biggy.
