### ISSUE TITLE
Restoration Druid Germination Talent

### ISSUE THREAD

**Issue by 693857** [brittyazel/EnhancedRaidFrames#4]
The level 100 Germination talent for Restoration Druids allows Rejuvenation to be cast twice on everyone, but there is no way to display this (its not a stack, its a second version on its own).

**Comment by brittyazel** [comment]
You're right, this has been an issue for a little while. Until I can fix this, please just put in Germination by the  spellID: 155777
That's what I do on my Restro Druid (main) and it works perfectly

**Comment by 693857** [comment]
Yes that works just fine, thank you for the suggestion!
