### ISSUE TITLE
Glow At Countdown Time doesn't reset

### ISSUE THREAD

**Issue by Amissia** [brittyazel/EnhancedRaidFrames#40]
Hey Britt,

Upgraded to 3.0 (Was super easy to copy over my settings because I'm a brain dead Holy Paladin) and was just going through the new options. I decided to test out the glow time because with my previous frames I would have them change colors based on glimmer duration and thought this would be a good replacement. I noticed that when reapplying the HoT to the target the glow time doesn't reset. And unlike my previous ticket, I supplied pictures this time. I'll be sure to submit more tickets if anything else pops up. Thank you. 

![14183bdef422e2ad2e2942e85dff7393](https://user-images.githubusercontent.com/67390796/85919426-dbd6b600-b81f-11ea-85c2-d50f16037698.png)
![097758d8b511b2331d2801ca4aad0175](https://user-images.githubusercontent.com/67390796/85919431-e09b6a00-b81f-11ea-9a4b-7a15151e7f05.png)
![8566993ec41627362e858e07e4aed3fb](https://user-images.githubusercontent.com/67390796/85919433-e2652d80-b81f-11ea-978f-14a8f2c791a5.png)

**Comment by brittyazel** [comment]
Nice catch, I'll sort it out and fix it asap. Thanks for testing and reporting!

**Comment by brittyazel** [comment]
Hrm, on a side note... There should be a profile option in the sidebar under Enhanced Raid Frames right after Icon Options... Hrm... That's concerning...
