### ISSUE TITLE
Conditional for an indicator based on spec.

### ISSUE THREAD

**Issue by eightflat** [brittyazel/EnhancedRaidFrames#41]
An example would be, let's say I want an indicator that shows when Unstable Affliction or Vampiric Touch are present on a target. Your addon perfectly allows for this and does it well, but then if I switch spec to DPS which can't dispel Magic. The indicator still shows. 

Love what you're doing by the way, keep it up :)

**Comment by brittyazel** [comment]
Yeah in the profile options you can set profiles per spec. If you enable that option you can make a DPS profile, copy it from your main, and then set it as your go to in your dps spec

**Comment by eightflat** [comment]
Hmm... feelin' pretty dumb for asking this, but I don't understand. You mean in the Blizzard Raid Profiles Menu? If so, I don't understand how the addon would discern between the Blizzard spec-based conditional?

**Comment by brittyazel** [comment]
No, within the Enhanced Raid Frames configuration settings is a panel called "Profiles", which allows you to switch different Enhanced Raid Frames profiles per spec and per character

**Comment by brittyazel** [comment]
![profileconfig](https://user-images.githubusercontent.com/3747347/86071331-db166d80-ba33-11ea-9d83-4fd3d84bdb2f.jpg)

**Comment by brittyazel** [comment]
![profileconfig (1)](https://user-images.githubusercontent.com/3747347/86071418-0731ee80-ba34-11ea-88cd-b71b83920db9.jpg)

**Comment by eightflat** [comment]
Wow, that's really odd. I have 3.1.1 installed and that option isn't there. I'll try to reinstall. Once again, you've predicted wanted features :)

**Comment by brittyazel** [comment]
Uh... What the hell? That's really really strange...

If ERF is the only add-on enabled does it show? Do you have any LUA errors? This is very weird. I had no idea that the profile option was missing for anyone.

Do you have any other unique things I should know? Are you using the English game client?

**Comment by eightflat** [comment]
English game client. yes. I use a fair bit of add-ons as you can see, but I think OmniCD is the only other one that directly interacts with the Blizzard Raid Frames (by way of anchoring to the frames). I'll check BugSack to see if it's reporting any LUA errors with ERF. And sorry, I didn't get a chance to reinstall yet, but I will work on it tomorrow and update :)

**Comment by brittyazel** [comment]
I doubt it's another add-on talk to the raid frames that's the issue. My
guess is that some add-on installed is supplying a broken or old version of
the library ace3-db-options

That's the only thing I can think of. If that library doesn't load then it
would make sense for the panel to not show. You'd think there'd be a LUA
error though. So a good test would be to see if you run ERH alone of the
problem still happens. Then if not, turn on each one at a time till you
find the culprit

**Comment by eightflat** [comment]
Not sure what you did, but I didn't have to reinstall and I can see Profiles for ERF now. Thank you for all your work, coffee inc :D

**Comment by brittyazel** [comment]
It's my please, and thanks a bunch :-) It's always appreciated!
