### ISSUE TITLE
Displaying dispel type via icon and some other small suggestions.

### ISSUE THREAD

**Issue by wow-dnb2** [brittyazel/EnhancedRaidFrames#44]
Hey, I've had a play about with the addon (for classic wow) and have it set up just right for what i want except for a few small things.

1. The icons i have being displayed through the add-on don't show the blue/green/purple border around the icons to show their dispel type. (for example, a blue border icon around polymorph) I tried every option but couldnt get this to show. i am using only the middle center indicator.

2. The icons are faded out when the person is out of range, if it would be possible to get an option to have indicator icons displayed always be at 100% visibility and not tied to the out of range fade variable it would be great.

3. If its possible to get a on screen movable text/icon warning similar to how the addon ''castannouncer'' works that says when one of the spells you have listed to be indicated has been applied to someone on your raid frames.
    The reason this would be nice is it would essentially be a reminder, telling you to look at your raid frames right when you need to and then you can locate said person in need of dispelling easier because we have the indicators. If possible adding in secondary option for only alerting when its people within 50-60 yards would be a very nice touch also .

Thank you very much for the addon. Hopefully these suggestions can help you improve it further!

**Comment by brittyazel** [comment]
Please don't put multiple requests in a single issue. It makes it super impossible to be systematic about addressing these feature requests. Please re-open these requests each in their own issue with as much information you can provide as possible, and I will address them in turn
