### ISSUE TITLE
Stack Positioning 

### ISSUE THREAD

**Issue by CDub619** [brittyazel/EnhancedRaidFrames#48]
The ability to move stack text positioning, around the raidframe for each icon , which would allow for positions shown below.
![AE9DEC1F-3553-4885-89FD-E27AD0BE6C02](https://user-images.githubusercontent.com/41877216/86502336-eb418c00-bd56-11ea-8452-8c0a2a99c12e.jpeg)

**Comment by brittyazel** [comment]
Is this a really sought after change? What's wrong with the text being in the center?

**Comment by CDub619** [comment]
This is the stacks, and it allows for easier viewing , when the stacks are attached to the time of the icon countdown text it can be confusing to digest.
