### ISSUE TITLE
wow classic

### ISSUE THREAD

**Issue by webphut** [brittyazel/EnhancedRaidFrames#54]
I am unable to get this to show up for wow classic in twitch.

**Comment by brittyazel** [comment]
Yes, it is not listed for WoW classic in twitch because Curseforge has serious breakages when you try to have the same add-on linked for both retail and classic. Until Curseforge fixes their system, I cannot fix this.

**Comment by joiglifberg** [comment]
Possibly time to review this? I've seen several addons that are linked to both retail and classic.

**Comment by brittyazel** [comment]
I know they announced that they would be adding classic and bcc support, but have they officially added it yet? I'm basically just waiting on that to go through once and for all

**Comment by joiglifberg** [comment]
I'm not sure but it looks like it to me. See the sidebar here for example https://www.curseforge.com/wow/addons/plater-nameplates

![image](https://user-images.githubusercontent.com/640695/142590858-dc190e76-ed01-4acd-a085-f95c22fd2719.png)
