### ISSUE TITLE
Timer for Greater Heal HOT (from priest t2 8/8) not working for other players

### ISSUE THREAD

**Issue by Anilusion** [brittyazel/EnhancedRaidFrames#55]
![image](https://user-images.githubusercontent.com/9070713/86902842-ca8a8500-c10e-11ea-8016-063830aa8a18.png)
The timer for Greater Heal HOT only shows if the heal is cast on yourself, not if you cast it on other players. The HOT has a proper duration on the target frame, but not in a raid frame indicator.

**Comment by brittyazel** [comment]
This seems like a libclassicdurations issue. In general, the game doesn't allow players in classic to query the length of other player's auras. A workaround for this is to use libclassicdurations, which is a library of how long each aura should last. What you are witnessing is the intended behavior by Blizzard. I'll check to see if libclassicdurations has an update for this, but it's outside of my control unfortunately, so I suggest you file that bug report with them directly

**Comment by Anilusion** [comment]
It's strange though, since the timer on my targetframe works, but the timer for the icon this addon creates does not.

**Comment by brittyazel** [comment]
It's just a limitation with Classic. The function that we use to get the length left on a buff, UnitAura(), is banned from returning that information to us. Hence why libclassicdurations exists. I don't make the rules sadly, this was a conscious choice Blizzard made.

**Comment by brittyazel** [comment]
I just pushed a new version of libclassicdurations to MASTER. Can you download the .zip here from Github, install it, test and see if that fixes your issue? If not, I suggest taking it up with the libclassicdurations author, and I'll gladly add his fixed version once the change is made

**Comment by Anilusion** [comment]
Awesome, it works with the latest version! Thank you.

**Comment by brittyazel** [comment]
👍
