### ISSUE TITLE
Localization FR : Indicator option panel is empty

### ISSUE THREAD

**Issue by ProogProog** [brittyazel/EnhancedRaidFrames#56]
The indicator options panel is empty :/
Thank you.
![panel](https://user-images.githubusercontent.com/68030613/86963263-84601080-c164-11ea-8aa0-c964269edb16.png)

**Comment by brittyazel** [comment]
Yep this was because there was an extra "new line" char in some of the strings. New version is being released now that will have this fixed

**Comment by ProogProog** [comment]
You are the best. Thanks =D
