### ISSUE TITLE
Show raid frames when not in a group

### ISSUE THREAD

**Issue by steven-joruk** [brittyazel/EnhancedRaidFrames#6]
Please enable this as it's more consistent than using the player frame only when outside of groups.

**Comment by brittyazel** [comment]
I'd love to, but this is on Blizzards end unfortunately. It is Blizzard that shows when the raid frames show, RFI only can act upon raid frames that already exist, not instantiate them itself. I wish I had better news :-/

**Comment by steven-joruk** [comment]
I'm probably missing something, but it looks like calling this seems to show the raid frames successfully, does this cause other problems?

```
/script CompactRaidFrameManager:Show()
/script CompactRaidFrameContainer:Show()
```

**Comment by brittyazel** [comment]
Hrm is it really that easy? I'll investigate and if it is really that easy it's probably reasonable to add a config option for this. The only thing I'm worried about is triggering this to show and then having :Hide called at some other random time. I'd have to hook the show/hide functions which can get messy

**Comment by steven-joruk** [comment]
This post from 2012 suggests it can taint the raid frames, but suggests another addon is able to work around it: https://eu.battle.net/forums/en/wow/topic/17613991229#post-2

I'll keep it enabled for a while and see if I get any errors.

**Comment by brittyazel** [comment]
Unfortunately this doesn't seem to be possible without extraordinary hacking to the default code. There is no elegant solution that doesn't result in copious amounts of taint :-/

I was really hoping this would work and I spent about 3 hours today trying my best to make it work, to no avail. The second you enter combat it all goes to hell.
