### ISSUE TITLE
Request: Solo raid frames

### ISSUE THREAD

**Issue by slapzlol** [brittyazel/EnhancedRaidFrames#60]
current addon I use for this has some errors ( https://www.curseforge.com/wow/addons/blizzard-raid-frames-solo-frame )
I think it would be a great optional extra in this addon and to cut down the number of add-ons and raid frame errors.

**Comment by brittyazel** [comment]
I've already looked into this and I'm sorry to say that it is really, really hard to get the raid frames to show full time. Every time I've tried to make it work it just ends up with non-stop taint errors. This is a behavior that Blizzard really doesn't want to happen, and they've put a lot of code in place to prevent it for whatever reason. Unfortunately, knowing that there's no solution here, at least for now, my hands are tied. I'm not going to implement anything that is overly hacky and prone to errors. 😕
