### ISSUE TITLE
Concatenate nil value error casting spell from a macro

### ISSUE THREAD

**Issue by CosmicCleric** [brittyazel/EnhancedRaidFrames#71]
## Issue description:
Targeting a training dummy, and call a macro that calls the (Affliction) Warlock spell "Mortal Coil" (while having a Felhunter pet out) generates an "attempt to concatenate local 'charges' (a nil value)" error.

_Note that I am not in a party or raid at the time of the error._

Here is the macro ...

/cast Mortal Coil

I've confirmed that the macro does succeed, and the target dummy gets the debuff generated by the casting of the Mortal Coil spell.

## How to reproduce:
1. Create a macro with one line in it, "/cast Mortal Coil".
2. Put the macro on an action bar (I used bottom-right bar).
3. Target a 'Training Dummy' NPC (I used the one in The Royal Armory in Zandalar/Dazar'alor).
4. Start combat by pressing the button that has the macro placed on it.
5. Error happens immediately (its an instant cast spell).

## Technical info:
 - **Addon Version:** *3.3.2*
 - **Client:** *Retail*
 - **Client Patch Version:** *9.0.2.36949*
 
## Additional context:
List of active addons when the error condition happens ...

> Details (DetailsRetail.9.0.2.8097.144)
> Enhanced Raid Frames (3.3.2)
> GTFO (4.57.1)
> MoveAnything (18.0.4)
> PetTracker (9.0.6)
> Scrap (9.0.1)
> TellMeWhen (9.0.3)
> TomTom (v90002-1.2.0)

All addons were installed via the "[Ajour](https://www.getajour.com/)" (version 0.5.4) Windows app (as discussed [here](https://www.wowhead.com/news=318208/ajour-open-source-simple-world-of-warcraft-addon-manager)).

## Screenshots:
N/A

## Lua error log:
Message: ...\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:877: attempt to concatenate local 'charges' (a nil value)
Time: Sun Dec 20 16:19:23 2020
Count: 5
Stack: ...\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:877: attempt to concatenate local 'charges' (a nil value)
[string "@Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua"]:877: in function `SendCooldownUpdate'
[string "@Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua"]:760: in function `?'
[string "@Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua"]:469: in function `TriggerEvent'
[string "@Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua"]:509: in function <...\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:508>

Locals: spellId = 6789
cooldownTimeLeft = nil
charges = nil
(*temporary) = "U"
(*temporary) = ","
(*temporary) = 6789
(*temporary) = ","
(*temporary) = nil
(*temporary) = ","
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'charges' (a nil value)"
CONST_COMM_COOLDOWNUPDATE_PREFIX = "U"
raidStatusLib = <table> {
 GetPlayerSpecId = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:54
 GetPlayerTalents = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:87
 commHandler = <table> {
 }
 IsInGroup = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:182
 IsCommAllowed = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:139
 gearManager = <table> {
 }
 specAttribute = <table> {
 }
 UnpackTable = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:149
 TCopy = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:104
 playerAlive = true
 playerInfoManager = <table> {
 }
 cooldownManager = <table> {
 }
 publicCallback = <table> {
 }
 PackTable = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:112
 RegisterCallback = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:409
 internalCallback = <table> {
 }
 CanReceiveComms = false
 UnregisterCallback = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:421
 inGroup = false
 UpdatePlayerAliveStatus = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:64
 mainControl = <table> {
 }
 Schedules = <table> {
 }
 isNearlyEqual = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:133
}
diagnosticComm = <function> defined @Interface\AddOns\Details\Libs\LibRaidStatus\LibRaidStatus.lua:47

**Comment by brittyazel** [comment]
I don't believe this bug applies to Enhanced Raid Frames. Your error says the bug comes from "LibRaidStatus" which is not a library that we use. In fact the error appears to be from the addon Details. I would suggest reporting this bug there.
