### ISSUE TITLE
Highlight frame when dispellable

### ISSUE THREAD

**Issue by the-isz** [brittyazel/EnhancedRaidFrames#78]
## Is your feature request related to a problem? Please describe:
I sometimes miss dispellable debuffs because they're not prominent enough on my screen.

## Describe the solution you'd like to see implemented:
I would like to be able to configure a glowing frame around a raid frame when the unit has a debuff that can be dispelled by me. 

## Describe alternatives you've considered:
I have already configured dispellable debuffs into a separate corner of the raid frame and increased their icon size. Sometimes, in the heat of battle, I still miss them though.

**Comment by brittyazel** [comment]
This is already an option. Please see the far right tab on the indicator configuration page and enable the spell highlight animation option. Cheers.

**Comment by the-isz** [comment]
I'm probably super-blind, but I can't seem to find it :/ Can you show me a screenshot, please?

**Comment by brittyazel** [comment]
Unfortunately I cannot right now, I'm away from my computer at a funeral for a few more days. You are looking for an option called "Indicator Glow Effect" on the "Animations" tab in the indicator configuration page. It's definitely there, I can promise you.
