### ISSUE TITLE
Spells missing after Action Bar Button #5

### ISSUE THREAD

**Issue by Stclv** [brittyazel/EnhancedRaidFrames#82]
```
[ADDON_ACTION_BLOCKED] AddOn 'EnhancedRaidFrames' hat versucht die geschützte Funktion 'ActionButton5:Show()' aufzurufen.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\ActionButton.lua"]:349: in function `Update'
[string "@FrameXML\ActionButton.lua"]:329: in function `UpdateAction'
[string "@FrameXML\ActionBarController.lua"]:132: in function `ActionBarController_UpdateAll'
[string "@FrameXML\ActionBarController.lua"]:64: in function <FrameXML\ActionBarController.lua:53>
```

sometimes after shapeshifting all action buttons after #5 disapear.

**Comment by brittyazel** [comment]
Despite what the lua error says, I don't believe Enhanced Raid Frames is responsible for your error. There no code in ERF that even remotely comes close to touching action bar buttons.

Have you tried with ERF disabled to see if it still happens? My bet is that it's one of your other addons

**Comment by Stclv** [comment]
That sounds good to me. I will take a deeper look in other addons. i will respond.
