### ISSUE TITLE
Mouse stops working when using Indicatior Options

### ISSUE THREAD

**Issue by Stiaar** [brittyazel/EnhancedRaidFrames#83]
Hi, I have been troubleshooting this issue for the past 3 hours but could get it working. Basically whenever I want to use Aura Watch List (any position), in this case Beacon of Virtue in the middle of a frame, whenever I mouseover and cast, my mouse gets disable and I can only move cursor. Clicking etc stops working and my screen is locked.

For raid frames, I only use base Blizzard unit frames and Clique.

Whenever I remove the spell from Aura Watch List it doesnt happen again.

## Technical info:
 - Addon Version: lastest
 - Client: Retail
 - Client Patch Version: lastest

Thank you

**Comment by brittyazel** [comment]
This should be fixed
