### ISSUE TITLE
Raid frame position settings stored in file possible?

### ISSUE THREAD

**Issue by SawyerMBlack** [brittyazel/EnhancedRaidFrames#86]
## Describe the solution you'd like to see implemented:
Raid frame positioning to my knowledge is stored server-side. There's another default raid frame addon out there, whose name I don't recall, that solves the issue and controls the positioning itself, allowing you to share the saved variables file to other characters to achieve the exact same position. Another addon that achieves this is Prat in regards to the chat window. I like having my characters pixel-perfect identical with UIs. Have you figured any way to achieve this?

**Comment by brittyazel** [comment]
If you use the profiles tab, you can import the profiles of any other of your characters. Likewise, we have the export string which you can use to import/export configurations from one character to the next. Unfortunately, the placement of the raid frames is not something that ERF controls, and it likely won't anytime soon.

Why not just create a UI profile using the built-in edit mode options that you load on each of your characters? I have all of my characters using the same profile so a change on one migrates to them all.
