### ISSUE TITLE
Default Buffs Are still being shown, There are no Options to Turn them off in the addon

### ISSUE THREAD

**Issue by Jangens1122** [brittyazel/EnhancedRaidFrames#92]
*When reporting, please verify the issue with only **this** addon enabled and no others unless explicitly reporting an incompatibility between this addon an another. Likewise, please fill in the below information to the best of your ability — this information helps us a great deal.*

## Issue description: The Addon it's self is working properly, And to be honest, I'm not sure if this is even a bug, But The default Buffs that show up on raid frames are still there with the addon enabled, I can't Find an option in the Addon settings, or in game to turn them off, so I feel like this is a bug.
![Raid frame bug](https://user-images.githubusercontent.com/117445711/199953786-2cb25b4a-cb75-41db-99db-7ad3b477034f.PNG)
)

*A clear and concise description of what the issue is (i.e. what went wrong and what should have happened).*

## How to reproduce:
*E.g., Steps to reproduce the behavior...*
1. *Go to '....'*
2. *Click on '....'*
3. *Scroll down to '....'*
4. *See error*

## Technical info:
 - **Addon Version:** *[e.g., 1.2.1]*
 - **Client:** *[e.g., Retail, Classic, PTR, or Beta]*
 - **Client Patch Version:** *[e.g., 9.0.1]*
 
## Additional context:
*Add any other context about the problem here.*

## Screenshots:
*If applicable, add screenshots to help explain your problem.*

## Lua error log:
*Attach the Lua error log here (please use code tags)*

**Comment by brittyazel** [comment]
There are options to turn them off on the mage page of the control panel. You have to click the main "Enhanced Raid Frames" item from the side menu in the config window. You can see pictures of these options on CurseForge.
