### ISSUE TITLE
Can't see more than the default 3 buffs

### ISSUE THREAD

**Issue by palla89** [brittyazel/EnhancedRaidFrames#93]
I can't understand why but I tried everything and I can't see more than 3 hots (resto druid) on the raid frame bar. Every option like sizing and such works correctly.
I have latest version. What am I doing wrong?

**Comment by brittyazel** [comment]
The stock buffs/debuffs only show 3. That was a design decision by Blizzard. Disable the stock buff and debuff icons if you don't want those to show and instead you can use ERFs indicators

**Comment by palla89** [comment]
Sorry but where are these options? I feel like an idiot for not finding them xD

**Comment by brittyazel** [comment]
![mainconfig](https://user-images.githubusercontent.com/3747347/200139485-a9a91216-1d30-4bc1-b7f5-d5670e68d352.jpg)
