### ISSUE TITLE
Out-of-Range Change

### ISSUE THREAD

**Issue by Rustcole** [brittyazel/EnhancedRaidFrames#98]
In the dropdown to select a custom distance for out-of-range, would it be possible to get this bumped up to 40 yards from the current max distance of 35? A lot of times I can still heal a greyed-out box because my spells are 40 yards in range, but my unit frames are telling me they are out of range because of the 35-yard distance. I am happy to change the code myself, but  I am not quite sure where this would be or if it's as easy a fix as I think it is. Any help with this would be greatly appreciated, I am currently wasting some time clicking to "test" whether my target is in range when it could just immediately let me know if it was just greyed out accurately at 40 yards. Thanks for the help! 

![image](https://user-images.githubusercontent.com/123160888/213668211-0d9aaa29-a094-4bb3-b784-dd9dec9093e7.png)

**Comment by brittyazel** [comment]
This was fixed a while ago, just getting around to closing it now.
